version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "10:00"
    timezone: Etc/UCT
  reviewers:
  - RandomByte
  - flovogt
  versioning-strategy: increase
  commit-message:
    prefix: "build(deps)"
    prefix-development: "build(devdeps)"
    include: "scope"
