name: "Fosstars (Security)"
on:
  workflow_dispatch:
  schedule:
    - cron: "36 4 * * *"

jobs:
  create_fosstars_report:
    runs-on: ubuntu-latest
    name: "Security rating"
    steps:
      - uses: actions/checkout@v3
      - name: Work around https://github.com/actions/checkout/issues/766
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE
      - uses: SAP/fosstars-rating-core-action@v1.9.0
        with:
          report-branch: fosstars-report
          token: "${{ secrets.GITHUB_TOKEN }}"
