name: "Fosstars (Security)"
on:
  workflow_dispatch:
  schedule:
    - cron: "36 4 * * *"

jobs:
  create_fosstars_report:
    runs-on: ubuntu-22.04
    name: "Security rating"
    steps:
      - uses: actions/checkout@v3
      - uses: SAP/fosstars-rating-core-action@v1.9.1
        with:
          report-branch: fosstars-report
          token: "${{ secrets.GITHUB_TOKEN }}"
