name: "Fosstars (Security)"
on:
  workflow_dispatch:
  schedule:
    - cron: "36 4 * * *"

jobs:
  create_fosstars_report:
    runs-on: ubuntu-22.04
    name: "Security rating"
    steps:
      - uses: actions/checkout@v4
      - uses: SAP/fosstars-rating-core-action@v1.14.0
        with:
          report-branch: fosstars-report
          git-user-name: "OpenUI5 Bot"
          git-user-email: "openui5@sap.com"
          token: ${{ secrets.GITHUB_TOKEN }}
