name: GitHub CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        version: [16, 18, 19]
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: General checks and tests
    runs-on: ${{ matrix.os }}
    steps:

    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.version }}

    - name: Install dependencies
      run: npm ci

    - name: Perfrom ESLint check
      run: npm run lint

    - name: Perform dependency check
      run: npm run depcheck

    - name: Run tests
      run: npm run coverage

    - name: Send report to Coveralls for package @ui5/middleware-code-coverage
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: middleware-code-coverage
        base-path: ./packages/middleware-code-coverage
        path-to-lcov: ./packages/middleware-code-coverage/coverage/lcov.info
