name: GitHub CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  checks:
    name: Linting, dependency check and unit tests
    runs-on: ubuntu-24.04
    steps:

    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.11.0

    - name: Install dependencies
      run: npm ci

    - name: Perfrom ESLint check
      run: npm run lint

    - name: Perfrom Licenses check
      run: npm run check-licenses

    - name: Perform dependency check
      run: npm run depcheck

    - name: Run unit tests
      run: npm run test:unit:coverage

    - name: Send report to Coveralls for package @ui5/middleware-code-coverage
      uses: coverallsapp/github-action@v2.3.6
      with:
        flag-name: middleware-code-coverage
        base-path: ./packages/middleware-code-coverage
        file: ./packages/middleware-code-coverage/coverage/lcov.info
