name: GitHub CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: General checks and tests
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Use Node.js LTS 16.x
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm ci

    - name: Perform checks and tests
      run: npm test

    - name: Send report to Coveralls for package @ui5/middleware-code-coverage
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: middleware-code-coverage
        base-path: ./packages/middleware-code-coverage
        path-to-lcov: ./packages/middleware-code-coverage/coverage/lcov.info
