on:
  workflow_dispatch:
    inputs:
      package-folder:
        description: 'The package to be released'
        required: true
        type: choice
        options:
          - middleware-code-coverage
  push:
    branches:
      - main
name: release-please
jobs:
  pull-request:
    runs-on: ubuntu-22.04
    outputs:
      releases_created: ${{steps.release.outputs.releases_created}}
      paths_released: ${{steps.release.outputs.paths_released}}
    steps:
    - uses: google-github-actions/release-please-action@v4
      id: release
      with:
        token: ${{secrets.GH_OPENUI5BOT}}
        path: packages/${{inputs.package-folder}}
  publish-package:
    needs: pull-request
    if: ${{needs.pull-request.outputs.releases_created && toJson(fromJson(needs.pull-request.outputs.paths_released)) != '[]'}}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        path_released: ${{fromJson(needs.pull-request.outputs.paths_released)}}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js LTS 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Publish to NPM
      env:
        NPM_TOKEN: ${{secrets.NPM_UI5BOT}}
      run: |
        cd ${{matrix.path_released}}
        echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> ./.npmrc
        npm publish --workspaces false --access public
