name: REUSE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
jobs:
  compliance-check:
    name: Compliance Check
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
    - name: Execute REUSE Compliance Check
      uses: fsfe/reuse-action@v5
