name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Unit and Integration
    strategy:
      matrix:
        version: [16, 18, 19.5.0]
        os: [ubuntu-22.04, windows-2022, macos-12]
    runs-on: ${{ matrix.os }}
    steps:

    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.version }}

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm run test:unit:coverage

    - name: Run integration tests
      run: npm run test:integration
